# Uncomment the next line to define a global platform for your project

platform :ios, '9.0'

target 'UseAsyncDisplayKit' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod "AsyncDisplayKit"
  pod "Kingfisher"
 
  target 'UseAsyncDisplayKitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UseAsyncDisplayKitUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
